<a href="https://colab.research.google.com/github/trulicups/mindmap/blob/main/courses/machine_learning/introduction_to_numby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a5 = [[x + y * 5 for x in range(5)] for y in range(5)]

a5

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [ ]:
a1000 = [[x + y * 5 for x in range(1000)] for y in range(1000)]

In [ ]:
def addToArray(i):
  for x_index in range(1000):
    for y_index in range(1000):
      a1000[x_index][y_index] += i

In [ ]:
%time addToArray(10)

CPU times: user 122 ms, sys: 0 ns, total: 122 ms
Wall time: 129 ms


In [ ]:
import numpy as np
arr = np.arange(1000000).reshape((1000,1000))
%time arr = arr + 10

CPU times: user 3.28 ms, sys: 11 µs, total: 3.29 ms
Wall time: 3.31 ms


In [ ]:
arr.mean()

500009.5

In [ ]:
arr.std()

288675.1345946685

In [ ]:
arr.sum()

500009500000

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
pythonArray = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

numpyArray = np.array(pythonArray)

numpyArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpyArray[1][2]

6

In [ ]:
numpyArray[1, 2]

6

In [ ]:
# python slices
a = [10, 20, 30, 40, 50, 60]
b = a[1:4] # a slice containing elements from indices 1 through 4, excluding the element at index 4

b

[20, 30, 40]

In [ ]:
numpy_a = np.array(a) # numpy copies by value and not by reference

numpy_b = numpy_a[1:4] # same logic as above

numpy_b

array([20, 30, 40])

python copies variables by **value**, not by reference

In [ ]:
b[1] = b[1] + 5

In [ ]:
b

[20, 35, 40]

In [ ]:
a

[10, 20, 30, 40, 50, 60]

numpy copies variables by **reference**, not by value

In [ ]:
numpy_b[1] = numpy_b[1] + 5

In [ ]:
numpy_b

array([20, 35, 40])

In [ ]:
numpy_a # the original ndarray is altered when the derived slice is altered

array([10, 20, 35, 40, 50, 60])

## simple numpy ndarray functions

### unary functions

In [ ]:
# absolute value
arr = np.array([-2, 12, -25, 0])
arr2 = np.abs(arr)
arr2

array([ 2, 12, 25,  0])

In [ ]:
# square
arr = np.array([-1, 2, -3, 4])
arr2 = np.square(arr)
arr2

array([ 1,  4,  9, 16])

In [ ]:
# square_root
arr = np.array([[4, 9], [16, 25]])
arr2 = np.sqrt(arr)
arr2

array([[2., 3.],
       [4., 5.]])

### binary functions

In [ ]:
# addition
arr1 = np.array([[10, 20], [30, 40]])
arr2 = np.array([[1, 2], [3, 4]])
np.add(arr1, arr2)

array([[11, 22],
       [33, 44]])

In [ ]:
# subtraction
np.subtract(arr1, arr2)

array([[ 9, 18],
       [27, 36]])

In [ ]:
# multiplication
np.multiply(arr1, arr2)

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
# division
np.divide(arr1, arr2)

array([[10., 10.],
       [10., 10.]])

In [ ]:
# maximum
arr1 = np.array([[10, 2], [3, 40]])
arr2 = np.array([[1, 20], [30, 4]])
np.maximum(arr1, arr2)

array([[10, 20],
       [30, 40]])

there are many more numpy functions

## numpy uber example

In [ ]:
driverLocations = np.array([[4, 5], [6, 6], [3, 1], [9, 5]])
driverLocations

array([[4, 5],
       [6, 6],
       [3, 1],
       [9, 5]])

In [ ]:
drivers = np.array(["personA", "personB", "personC", "personD"])

In [ ]:
customer = np.array([6, 3])

In [ ]:
driverDistances = driverLocations - customer
driverDistances

array([[-2,  2],
       [ 0,  3],
       [-3, -2],
       [ 3,  2]])

In [ ]:
driverDistances = np.abs(driverDistances).sum(axis = 1)
driverDistances

array([4, 3, 5, 5])

In [ ]:
sorted = np.argsort(driverDistances) # returns an array of indices sorted by the values referenced by the indices
sorted

array([1, 0, 2, 3])

In [ ]:
drivers[sorted[0]]

'personB'

In [ ]:
def findDriver(distanceArr, driversArr, customerArr):
  result = ''

  xydiff = distanceArr - customerArr
  distanceArr = np.abs(xydiff).sum(axis = 1)

  sort = np.argsort(distanceArr)
  
  result = drivers[sort[0]]

  return result

print(findDriver(driverLocations, drivers, customer)) # this should return `personB`

personB


In [ ]:
customers = np.array([[4, 5, 2, 1, 3],
                      [3, 1, 5, 4, 2],
                      [5, 5, 2, 2, 3],
                      [4, 1, 4, 4, 1], 
                      [1, 1, 5, 4, 1],
                      [4, 5, 3, 3, 1]])

customerNames = np.array(["Ann", "Ben", 'Jordyn', "Sam", "Hyunseo", "Ahmed"])

mikaela = np.array([3, 2, 4, 5, 4])
patrik = np.array([4, 5, 1, 2, 3])


In [ ]:
def findClosest(customers, customerNames, evalCustomer):
  arrDiff = customers - evalCustomer

  distanceArr = np.abs(arrDiff).sum(axis = 1)

  sorted = np.argsort(distanceArr)

  return customerNames[sorted[0]]

In [ ]:
findClosest(customers, customerNames, mikaela)

'Ben'

In [ ]:
findClosest(customers, customerNames, patrik)

'Ann'

In [ ]:
locations = np.array([[4, 5], [6, 6], [3, 1], [9, 5]])
drones = np.array(["wing_1a", "wing_2a", "wing_3a", "wing_4a"])
customer = np.array([6, 3])

def euclidean(droneLocation, droneNames, x):
  result = ''

  distanceArr = np.square((droneLocation - x)).sum(axis = 1)

  result = droneNames[np.argsort(distanceArr)[0]]

  return result

euclidean(locations, drones, customer)

[ 8  9 13 13]


'wing_1a'